data_path: ../data/raw
file: tv001_coefficient_reduction_deperditions.csv
filters:
- col: aiu_aue
  function: "lambda x: '<' in str(x) or '?' in str(x)"
keys:
- key_name: aiu_aue_max
  key_type: num
- key_name: aue_isole
  key_type: cat
- key_name: aiu_isole
  key_type: cat
- key_name: uv_ue
  key_type: num
mapping:
- col: aiu_aue_max
  function: 'lambda x: x if not(np.isnan(x)) else 100'
- col: aue_isole
  function: 'lambda x: "yes" if x == 1 else "no"' # Always no when computing isolation
- col: aiu_isole
  function: 'lambda x: "yes" if x == 1 else "no"' # Always no when computing isolation
values:
- valeur