# Description: Configuration file
# Order of the operations: rename -> filter -> refs -> mapping -> reduce
data_path: ../data/raw
file: tv019bis_fecs.csv
keys:
- key_name: type_batiment
  key_type: cat
- key_name: type_installation
  key_type: cat
- key_name: zone_climatique
  key_type: cat
values:
- fecs
