# Description: Configuration file
# Order of the operations: rename -> filter -> refs -> mapping -> reduce
data_path: ../data/raw
file: tv014_bis_permeabilite.csv
keys:
- key_name: type_batiment
  key_type: cat
- key_name: annee_construction_max
  key_type: num
values:
- q4paconv
