# Description: Configuration file
# Order of the operations: rename -> filter -> refs -> mapping -> reduce
data_path: ../data/raw
file: tv028_rendement_emission_systeme_chauffage.csv
keys:
- key_name: type_emetteur
  key_type: cat
values:
- re