# Description: Configuration file
# Order of the operations: rename -> filter -> refs -> mapping -> reduce
data_path: ../data/raw
file: tv005bis_upb_terre_plein.csv
keys:
- key_name: type
  key_type: cat
- key_name: 2S/P
  key_type: num
- key_name: Upb
  key_type: num
values:
- Value
