# Description: Configuration file
# Order of the operations: rename -> filter -> refs -> mapping -> reduce
data_path: ../data/raw
file: tv033_coefficient_correction_regulation.csv
keys:
- key_name: emetteur
  key_type: cat
values:
- c_regul