# Description: Configuration file
# Order of the operations: rename -> filter -> refs -> mapping -> reduce
data_path: ../data/raw
file: tv047bis_rendement_generation_ecs.csv
keys:
- key_name: annee_generateur
  key_type: num
- key_name: puissance_nominale
  key_type: cat
rename:
  ancienneté: annee_generateur
values:
- Rpn
- Qp0
- Pveilleuse