# Description: Configuration file
# Order of the operations: rename -> filter -> refs -> mapping -> reduce
data_path: ../data/raw
file: tv006_upb0.csv
keys:
- key_name: materiaux
  key_type: cat
values:
- upb0
